name: Update Data

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 15 * *"

jobs:
  Update:
    environment: CI
    runs-on: ubuntu-latest
    steps:
    - name: Add Package GitHub Action Metadata
      uses: actions/checkout@v3
    - name: Add Package GitHub NodeJS Setup
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Installing Package
      run: npm install
    - name: Updating All Datas
      run: npm run update
    - name: Creating Commit
      run: |
        date > last-update.txt
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "update_data_auto"
        git push
        curl ${{ secrets.HEARTBEAT }}