name: Update Data

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 15 * *"

jobs:
  Update:
    environment: CI
    runs-on: ubuntu-latest
    steps:
    - name: Add Package GitHub Action Metadata
      uses: actions/checkout@v3
    - name: Add Package GitHub NodeJS Setup
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Installing Package
      run: npm install
    - name: Updating All Datas
      run: |
        npm run update
        date > last-update.txt
    - name: Creating Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: sync_data_emoji
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
